name: Build & publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Log in to GitHub container registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image to GitHub registry
      uses: docker/build-push-action@v5
      with:
        provenance: false
        push: true
        tags: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-gemini-1-0-pro:latest
        file: ./Dockerfile